import React from "react";

const langEn = {
  headerTitle: "Read, Play & Win",
  read_play_win: "Read, Play & Win",
  login_header_2: "Lire un livre et jouer aux quiz !",
  welcome_to_quizzito: "Bienvenue a Quizzito",
  quizzito: "Quizzito",
  use_card: "Utilise ta carte pour ce connecter",
  start_btn: "Commencer",
  continue_btn: "CONTINUER",
  confirmation: "CONFIRMATION",
  confirm_btn: "CONFIRMER",
  log_in_btn: "CONNECTER",
  pick_a_book_btn: "CHOISIR UN LIVRE",
  pick_other_book: "CHOISIR UN AUTRE LIVRE",
  read: "Lire",
  another_book: "UN AUTRE LIVRE",
  user_name_placeholder: "Nom d'utilisateur sur la carte",
  passowrd_placeholder: "Mot de passe sur la carte",
  ranking_label: "Classement",
  read_book_lablel: "Lire des Livres",
  points_label: "Points",
  msg_leave_game:
    "Vous pouvez revenir pour terminer le quiz plus tard, mais vous perdrez la question en cours.",
  msg_confirm_play_quiz:
    "Vous avez lu ce livre et vous souhaitez faire son quiz ?",
  msg_leave_game_title: "ÊTES-VOUS SR DE VOULOIR PARTIR ?",
  level_label: "Niveau",
  leave_btn: "SORTIR",
  play_btn: "JOUER",
  yes_btn: "OUI",
  no_btn: "NON",
  books_read: "Livres Lus",
  show_your_card: "Montrez votre carte à la caméra",
  show_book_qr: "Montrez le code QR de votre livre à l'appareil photo",
  after_quiz_msg1_1: "Le joueur à la deuxième place n'a besoin que de",
  after_quiz_msg1_2:
    "points pour prendre votre place, en savoir plus pour rester le premier",
  after_quiz_msg2_1: "Tu a juste besoins de ",
  after_quiz_msg2_2: "point(s) pour etre classer",
  after_quiz_msg3:
    "Vous êtes le premier participant à la compétition, restez concentré pour conserver votre première place.",
  score_alert_1: "Allez!",
  score_alert_2: "Lire et jouer",
  score_alert_3: "Concentrez-vous davantage",
  score_alert_4: "Bon travail",
  score_alert_5: "Wooow!",
  user_info_phone: "Écris le numéro de téléphone de tes parents",
  user_info_full_name: "Écrivez votre nom complet",
  user_info_first_name: "Écrivez votre prénom",
  user_info_last_name: "Écrivez votre nom de famille",
  next: "Suivant",
};
export default langEn;
