import React from "react";

const langAr = {
  headerTitle: "إقرأ، إلعب واربح",
  read_play_win: "إقرأ، إلعب واربح",
  login_header_2: "إقرأ الكتاب والعب على الكويز",
  welcome_to_quizzito: "مرحبا بك بعالم كويزيتو",
  quizzito: "كويزيتو",
  use_card: "أظهر البطاقة للدخول",
  start_btn: "انطلق",
  continue_btn: "المواصلة",
  confirmation: "تأكيد",
  confirm_btn: "تأكيد",
  log_in_btn: "الدخول",
  pick_a_book_btn: "إختر الكتاب",
  pick_other_book: "إختر كتابا آخر",
  read: "إقرأ",
  another_book: "كتابا آخر",
  user_name_placeholder: "إسم المستخدم الموجود بالبطاقة",
  passowrd_placeholder: "كلمة المرور الموجودة بالبطاقة",
  ranking_label: "الترتيب",
  read_book_lablel: "الكتب المقروءة",
  points_label: "النقاط",
  msg_leave_game:
    "بإمكانك مواصلة الأسئلة المتبقية لاحقا، علما أنك ستخسر السؤال الحالي.",
  msg_confirm_play_quiz: "هل قرأت الكتاب جيدا وتريد اللعب على الكويز؟",
  msg_leave_game_title: "هل تريد الخروج؟",
  level_label: "مستوى",
  leave_btn: "خروج",
  play_btn: "إلعب",
  yes_btn: "نعم",
  no_btn: "لا",
  books_read: "الكتب المقروءة",
  show_your_card: "أظهر بطاقتك للكاميرا",
  show_book_qr: "أظهر بطاقة الكتاب للكاميرا",
  after_quiz_msg1_1: "سيلحق بك اللاعب الثاني إذا حصل على ",
  after_quiz_msg1_2: "نقطة، إقرأ أكثر لتحافظ على مرتبتك الأولى",
  after_quiz_msg2_1: "تحتاج",
  after_quiz_msg2_2: "نقطة فقط ليصبح ترتيبك",
  after_quiz_msg3: "أنت بالمركز الأول، إقرأ وركز أكثر لتحافظ على مرتبتك",
  score_alert_1: "هل أنت بخير؟",
  score_alert_2: "إقرأ ثم إلعب",
  score_alert_3: "ركز أكثر",
  score_alert_4: "أداء حسن",
  score_alert_5: "واااو!",
  user_info_phone: "أكتب رقم والدتك أو والدك",
  user_info_full_name: "أكتب إسمك الكامل",
  user_info_first_name: "اكتب اسمك",
  user_info_last_name: "أكتب إسم العائلة",
  next: "التالي",
};

export default langAr;
